# Generated by Django 5.2 on 2025-04-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('админ', 'Админ'), ('бухгалтер', 'Бухгалтер'), ('естокада', 'Естокада'), ('финансист', 'Финансист')], default='Бухгалтер', max_length=20),
        ),
    ]
