# Generated by Django 5.2 on 2025-04-24 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_bio_user_phone_number_user_profile_image_and_more'),
        ('blog', '0007_alter_option_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('type', models.CharField(choices=[('videos_watched', 'Просмотр видео'), ('tests_passed', 'Прохождение тестов'), ('perfect_score', 'Идеальный результат'), ('login_streak', 'Серия входов'), ('category_complete', 'Завершение категории'), ('level_reached', 'Достижение уровня')], max_length=30, verbose_name='Тип')),
                ('icon', models.ImageField(upload_to='achievement_icons/', verbose_name='Иконка')),
                ('required_value', models.IntegerField(verbose_name='Требуемое значение')),
                ('experience_reward', models.IntegerField(default=50, verbose_name='Награда опытом')),
                ('is_secret', models.BooleanField(default=False, verbose_name='Секретное достижение')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='experience_points',
            field=models.IntegerField(default=0, verbose_name='Очки опыта'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('certificate_id', models.CharField(max_length=50, unique=True, verbose_name='Номер сертификата')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='LevelUpEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_level', models.IntegerField(verbose_name='Предыдущий уровень')),
                ('new_level', models.IntegerField(verbose_name='Новый уровень')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время повышения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_up_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_viewed', models.DateTimeField(auto_now=True, verbose_name='Последний просмотр')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Категория завершена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('posts_viewed', models.ManyToManyField(related_name='viewed_by_progress', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('current_value', models.IntegerField(default=0, verbose_name='Текущее значение')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
