# Generated by Django 5.2 on 2025-04-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('бухгалтер', 'Buxgalter'), ('естокада', 'Estakada'), ('финансист', 'Finansist'), ('Оператор', 'Operator'), ('Диспетчер', 'Dispatcher'), ('охраник', 'Qorovul'), ('уборщик', 'tozalovchi'), ('повар', 'Povar'), ('технолог', 'Texnolog'), ('сварщик', 'Svarshchi'), ('электрик', 'Elektrik'), ('механик', 'Mexanik'), ('КИП и А', 'KIP i A'), ('бензин отдела', 'Benzina otdeli'), ('склад', 'Sklad')], default='бухгалтер', max_length=20, verbose_name='Foydalanuvchi roli'),
        ),
    ]
