# Generated by Django 5.2 on 2025-04-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_achievement_user_experience_points_user_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Продолжительность активности в минутах', verbose_name='Продолжительность'),
        ),
    ]
