# Generated by Django 5.2 on 2025-05-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('офисный-персонал', 'ofis-xodimlari'), ('естокада', 'Ishlab-chiqarish'), ('Оператор', 'Operator'), ('Диспетчер', 'Dispatcher'), ('охраник', 'Qorovul'), ('уборщик', 'Tozalovchi'), ('повар', 'Oshpaz'), ('технолог', 'Muhandis'), ('сварщик', 'Payvandlovchi'), ('электрик', 'Elektromontyor'), ('механик', 'Mexanik'), ('КИП и А', 'KIP i A'), ('бензин отдела', 'Benzina bo`limi'), ('склад', 'Sklad'), ('слесарь', 'Chilangar'), ('temiryo`lchi', 'Temiryo`lchi')], default='офисный-персонал', max_length=20, verbose_name='Foydalanuvchi roli'),
        ),
    ]
