# Generated by Django 5.2 on 2025-04-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='role',
            field=models.CharField(choices=[('бухгалтер', 'Buxgalter'), ('естокада', 'Estakada'), ('финансист', 'Finansist')], default='бухгалтер', max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='role',
            field=models.CharField(choices=[('бухгалтер', 'Buxgalter'), ('естокада', 'Estakada'), ('финансист', 'Finansist')], max_length=20, verbose_name='Foydalanuvchi roli'),
        ),
    ]
