# Generated by Django 5.2 on 2025-04-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_role_alter_test_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='role',
            field=models.CharField(choices=[('бухгалтер', 'Buxgalter'), ('естокада', 'Estakada'), ('финансист', 'Finansist'), ('Оператор', 'Operator'), ('Диспетчер', 'Dispatcher'), ('охраник', 'Qorovul'), ('уборщик', 'tozalovchi'), ('повар', 'Povar'), ('технолог', 'Texnolog'), ('сварщик', 'Svarshchi'), ('электрик', 'Elektrik'), ('механик', 'Mexanik'), ('КИП и А', 'KIP i A'), ('бензин отдела', 'Benzina otdeli'), ('склад', 'Sklad'), ('слесарь', 'Slesar')], default='бухгалтер', max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='role',
            field=models.CharField(choices=[('бухгалтер', 'Buxgalter'), ('естокада', 'Estakada'), ('финансист', 'Finansist'), ('Оператор', 'Operator'), ('Диспетчер', 'Dispatcher'), ('охраник', 'Qorovul'), ('уборщик', 'tozalovchi'), ('повар', 'Povar'), ('технолог', 'Texnolog'), ('сварщик', 'Svarshchi'), ('электрик', 'Elektrik'), ('механик', 'Mexanik'), ('КИП и А', 'KIP i A'), ('бензин отдела', 'Benzina otdeli'), ('склад', 'Sklad'), ('слесарь', 'Slesar')], max_length=20, verbose_name='Foydalanuvchi roli'),
        ),
    ]
