# Generated by Django 5.2 on 2025-04-23 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_analytics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analytics',
        ),
    ]
