# Generated by Django 5.2 on 2025-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_question_test_option_question_test_testresult_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Javob varianti', 'verbose_name_plural': 'Javob variantlari'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Test', 'verbose_name_plural': 'Testlar'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Test natijasi', 'verbose_name_plural': 'Test natijalari'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Foydalanuvchi javobi', 'verbose_name_plural': 'Foydalanuvchi javoblari'},
        ),
        migrations.AlterField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name="To'g'ri variant"),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Variant matni'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Javob izohi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Savol matni'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(verbose_name='Test tavsifi'),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='test',
            name='passing_score',
            field=models.IntegerField(default=70, verbose_name="O'tish bali (%)"),
        ),
        migrations.AlterField(
            model_name='test',
            name='role',
            field=models.CharField(choices=[('админ', 'Админ'), ('бухгалтер', 'Бухгалтер'), ('естокада', 'Естокада'), ('финансист', 'Финансист')], max_length=20, verbose_name='Foydalanuvchi roli'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(default=30, verbose_name='Vaqt chegarasi (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Test nomi'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='completed_at',
            field=models.DateTimeField(verbose_name='Yakunlangan vaqt'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name="Test o'tilgan"),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='percentage',
            field=models.FloatField(verbose_name="To'g'ri javoblar foizi"),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.FloatField(verbose_name='Ball miqdori'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='started_at',
            field=models.DateTimeField(verbose_name='Boshlangan vaqt'),
        ),
    ]
