# Generated by Django 3.2.22 on 2025-08-16 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_alter_post_role_alter_test_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Hujjat nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Fayl')),
                ('allowed_roles', models.JSONField(default=list, verbose_name='Ruxsat berilgan rollar')),
                ('is_public', models.BooleanField(default=False, verbose_name='Barcha foydalanuvchilar uchun ochiq')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fayl hajmi (bayt)')),
                ('file_type', models.CharField(blank=True, max_length=10, verbose_name='Fayl turi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Yuklab olishlar soni')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('icon', models.CharField(default='fas fa-folder', max_length=50, verbose_name='Ikonka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Hujjat kategoriyasi',
                'verbose_name_plural': 'Hujjat kategoriyalari',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('офисный-персонал', 'ofis-xodimlari'), ('естокада', 'Ishlab-chiqarish'), ('Оператор', 'Operator'), ('Диспетчер', 'Dispatcher'), ('охраник', 'Qorovul'), ('уборщик', 'Tozalovchi'), ('повар', 'Oshpaz'), ('технолог', 'Muhandis'), ('сварщик', 'Payvandlovchi'), ('электрик', 'Elektromontyor'), ('механик', 'Mexanik'), ('КИП и А', 'KIP i A'), ('склад', 'Sklad'), ('слесарь', 'Chilangar'), ('temiryo`lchi', 'Temiryo`lchi')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('офисный-персонал', 'ofis-xodimlari'), ('естокада', 'Ishlab-chiqarish'), ('Оператор', 'Operator'), ('Диспетчер', 'Dispatcher'), ('охраник', 'Qorovul'), ('уборщик', 'Tozalovchi'), ('повар', 'Oshpaz'), ('технолог', 'Muhandis'), ('сварщик', 'Payvandlovchi'), ('электрик', 'Elektromontyor'), ('механик', 'Mexanik'), ('КИП и А', 'KIP i A'), ('склад', 'Sklad'), ('слесарь', 'Chilangar'), ('temiryo`lchi', 'Temiryo`lchi')], max_length=20, verbose_name='Foydalanuvchi roli'),
        ),
        migrations.CreateModel(
            name='DocumentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name="Ko'rilgan vaqt")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blog.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Hujjat ko'rish",
                'verbose_name_plural': "Hujjat ko'rishlar",
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklab olingan vaqt')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='blog.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hujjat yuklab olish',
                'verbose_name_plural': 'Hujjat yuklab olishlar',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='blog.documentcategory', verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan foydalanuvchi'),
        ),
    ]
