# Generated by Django 5.2 on 2025-04-25 06:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ikonka kodi')),
            ],
            options={
                'verbose_name': 'Kurs kategoriyasi',
                'verbose_name_plural': 'Kurs kategoriyalari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Dars nomi')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('lesson_type', models.CharField(choices=[('video', 'Video dars'), ('text', 'Matnli dars'), ('quiz', 'Test'), ('assignment', 'Vazifa')], default='video', max_length=20, verbose_name='Dars turi')),
                ('video_url', models.URLField(blank=True, verbose_name='Video havolasi')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='courses/videos/', verbose_name='Video fayl')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Daqiqalardagi davomiyligi', verbose_name='Davomiyligi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_free_preview', models.BooleanField(default=False, verbose_name="Bepul ko'rish uchun")),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Izohlar ruxsat etilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kurs nomi')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('short_description', models.CharField(max_length=255, verbose_name='Qisqa tavsif')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='courses/covers/', verbose_name='Muqova rasmi')),
                ('difficulty', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], default='beginner', max_length=20, verbose_name='Qiyinlik darajasi')),
                ('duration', models.PositiveIntegerField(help_text='Daqiqalardagi taxminiy davomiyligi', verbose_name='Davomiyligi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr qilingan'), ('archived', 'Arxivlangan')], default='draft', max_length=20, verbose_name='Holati')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Narxi')),
                ('is_free', models.BooleanField(default=True, verbose_name='Bepul')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.coursecategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan sana")),
                ('is_completed', models.BooleanField(default=False, verbose_name='Yakunlangan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan sana')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Kurs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kursga yozilish',
                'verbose_name_plural': 'Kursga yozilishlar',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True, verbose_name='Sertifikat ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sertifikat nomi')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='Berilgan sana')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/courses/', verbose_name='PDF fayl')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='certificates/preview/', verbose_name="Ko'rish rasmi")),
                ('certificate_type', models.CharField(default='course', max_length=20, verbose_name='Sertifikat turi')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses.enrollment', verbose_name='Kursga yozilish')),
            ],
            options={
                'verbose_name': 'Kurs sertifikati',
                'verbose_name_plural': 'Kurs sertifikatlari',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Fayl nomi')),
                ('file', models.FileField(upload_to='courses/attachments/', verbose_name='Fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.lesson', verbose_name='Dars')),
            ],
            options={
                'verbose_name': 'Dars ilovasi',
                'verbose_name_plural': 'Dars ilovalari',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Modul nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='Modul'),
        ),
        migrations.CreateModel(
            name='CompletedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Yakunlangan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_lessons', to='courses.enrollment', verbose_name='Kursga yozilish')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='courses.lesson', verbose_name='Dars')),
            ],
            options={
                'verbose_name': 'Yakunlangan dars',
                'verbose_name_plural': 'Yakunlangan darslar',
                'ordering': ['-completed_at'],
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
    ]
