# Generated by Django 5.2 on 2025-04-24 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedlesson',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Yakunlangan dars', 'verbose_name_plural': 'Yakunlangan darslar'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='coursecertificate',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursecertificate',
            name='user',
        ),
        migrations.AddField(
            model_name='completedlesson',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='completed_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecertificate',
            name='enrollment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses.enrollment', verbose_name='Kursga yozilish'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completedlesson',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_lessons', to='courses.enrollment', verbose_name='Kursga yozilish'),
        ),
        migrations.AlterField(
            model_name='completedlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='courses.lesson', verbose_name='Dars'),
        ),
    ]
