# Generated by Django 5.2 on 2025-04-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_completedlesson_options_remove_course_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='Izohlar ruxsat etilgan'),
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Fayl nomi')),
                ('file', models.FileField(upload_to='courses/attachments/', verbose_name='Fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.lesson', verbose_name='Dars')),
            ],
            options={
                'verbose_name': 'Dars ilovasi',
                'verbose_name_plural': 'Dars ilovalari',
                'ordering': ['created_at'],
            },
        ),
    ]
